baseURL = "https://ghostlog.space"
languageCode = 'en-us'
theme = 'hugo-bearblog'
title = "a log floating in tha net"
pagination.pagerSize = 10

[menus]
[[menus.main]]
  name = 'about'
  pageRef = '_about'
[[menus.main]]
  name = 'blog'
  pageRef = 'posts'
[[menus.main]]
  name = 'tags'
  pageRef = 'tags'

[markup]
  [markup.highlight]
    codeFences = true # default = true
    noClasses = false # default = true
    lineNumbersInTable = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # This is *necessary* for ox-hugo to work well with Hugo 0.60.0+